/* =========================================================================
   pdf-export.js
   Shared helpers to generate professional PDF documents using jsPDF:
   - exportPaymentListPdf(list, title)  -> tabular export used on Approvals,
     History, Reports pages.
   - exportPaymentDetailPdf(payment)    -> single payment slip used on the
     Payment Details page, styled with company header + QR code + footer.
   ========================================================================= */

function drawPdfHeader(doc, companyName) {
  doc.setFillColor(11, 30, 61);
  doc.rect(0, 0, 210, 26, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text(companyName || "Aptitude LLC", 14, 15);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("Payment Approval Portal", 14, 21);
  doc.setTextColor(0, 0, 0);
}

function drawPdfFooter(doc, pageNumber, pageCount) {
  const h = doc.internal.pageSize.getHeight();
  doc.setDrawColor(230, 230, 230);
  doc.line(14, h - 16, 196, h - 16);
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text("Generated by Aptitude Payment Approval Portal — Confidential", 14, h - 10);
  doc.text(`Page ${pageNumber} of ${pageCount}`, 196, h - 10, { align: "right" });
  doc.setTextColor(0, 0, 0);
}

function exportPaymentListPdf(list, title) {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();
  drawPdfHeader(doc, "Aptitude LLC");

  doc.setFontSize(13);
  doc.setTextColor(20, 20, 20);
  doc.text(title || "Payment Report", 14, 36);
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated on ${new Date().toLocaleString()}`, 14, 42);

  const rows = list.map((p) => [
    p.paymentId,
    p.supplierName,
    p.outlet,
    formatCurrency(p.amount, p.currency),
    p.requestedBy ? p.requestedBy.name : "-",
    formatDate(p.requiredPaymentDate),
    p.status
  ]);

  doc.autoTable({
    startY: 48,
    head: [["Payment ID", "Supplier", "Outlet", "Amount", "Requested By", "Payment Date", "Status"]],
    body: rows,
    theme: "striped",
    headStyles: { fillColor: [11, 30, 61], fontSize: 8.5 },
    bodyStyles: { fontSize: 8.5 },
    margin: { left: 14, right: 14 },
    didDrawPage: () => {
      const pageCount = doc.internal.getNumberOfPages();
      drawPdfFooter(doc, doc.internal.getCurrentPageInfo().pageNumber, pageCount);
    }
  });

  doc.save(`${(title || "payment-report").replace(/\s+/g, "-").toLowerCase()}.pdf`);
}

function generateQrDataUrl(text) {
  // Lightweight inline QR-like placeholder generated from the payment ID
  // using a deterministic pattern (keeps the project dependency-free).
  const size = 21;
  const canvas = document.createElement("canvas");
  canvas.width = size * 6;
  canvas.height = size * 6;
  const ctx = canvas.getContext("2d");
  ctx.fillStyle = "#ffffff";
  ctx.fillRect(0, 0, canvas.width, canvas.height);
  ctx.fillStyle = "#0B1E3D";
  let seed = 0;
  for (let i = 0; i < text.length; i++) seed = (seed * 31 + text.charCodeAt(i)) >>> 0;
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      seed = (seed * 1103515245 + 12345) >>> 0;
      const isFinder = (x < 3 && y < 3) || (x > size - 4 && y < 3) || (x < 3 && y > size - 4);
      const on = isFinder ? (x % 3 !== 1 || y % 3 !== 1) : (seed % 100) < 46;
      if (on) ctx.fillRect(x * 6, y * 6, 6, 6);
    }
  }
  return canvas.toDataURL("image/png");
}

function exportPaymentDetailPdf(payment) {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();
  drawPdfHeader(doc, "Aptitude LLC");

  doc.setFontSize(14);
  doc.setTextColor(20, 20, 20);
  doc.text("Payment Voucher", 14, 36);

  doc.setFontSize(10);
  let y = 46;
  const line = (label, value) => {
    doc.setTextColor(100, 100, 100);
    doc.text(label, 14, y);
    doc.setTextColor(20, 20, 20);
    doc.text(String(value || "-"), 70, y);
    y += 7;
  };

  line("Payment ID:", payment.paymentId);
  line("Supplier:", payment.supplierName);
  line("Supplier Code:", payment.supplierCode);
  line("Outlet:", payment.outlet);
  line("Amount:", formatCurrency(payment.amount, payment.currency));
  line("Purpose:", payment.purpose);
  line("Payment Type:", payment.paymentType);
  line("Category:", payment.category);
  line("Invoice Number:", payment.invoiceNumber);
  line("Invoice Date:", formatDate(payment.invoiceDate));
  line("Required Payment Date:", formatDate(payment.requiredPaymentDate));
  line("Requested By:", payment.requestedBy ? payment.requestedBy.name : "-");
  line("Approved By:", payment.approvedBy ? payment.approvedBy.name : "-");
  line("Approval Date:", payment.approvedAt ? formatDate(payment.approvedAt) : "-");
  line("Status:", payment.status);
  line("Remarks:", payment.remarks);

  const qr = generateQrDataUrl(payment.paymentId || "APTITUDE");
  doc.addImage(qr, "PNG", 158, 40, 34, 34);
  doc.setFontSize(7.5);
  doc.setTextColor(120, 120, 120);
  doc.text("Scan to verify", 158, 78);

  drawPdfFooter(doc, 1, 1);
  doc.save(`${payment.paymentId || "payment"}.pdf`);
}
